# Generated by Django 4.0.4 on 2022-05-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
