# Generated by Django 4.0.4 on 2022-07-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_genre_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemahall',
            options={'verbose_name': 'cinema_hall', 'verbose_name_plural': 'cinema_halls'},
        ),
    ]
