# Generated by Django 4.0.4 on 2023-03-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_genre_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemahall',
            options={'verbose_name': 'cinema_hall'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title'], 'verbose_name': 'movie_session'},
        ),
    ]
