# Generated by Django 4.0.4 on 2024-02-16 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_movie_options_cinemahall_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='rows',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='seats_in_row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='show_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
