# Generated by Django 4.0.4 on 2024-02-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_alter_cinemahall_capacity_alter_cinemahall_rows_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemahall',
            name='capacity',
        ),
    ]
