# Generated by Django 4.2.2 on 2023-06-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_actor_cinemahall_genre_movie_moviesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='moviesession',
            name='cinema_hall',
        ),
        migrations.RemoveField(
            model_name='moviesession',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='CinemaHall',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieSession',
        ),
    ]
